[2025-05-28T08:53:58.839+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_etl_pipeline.analyze_data scheduled__2025-05-27T06:00:00+00:00 [queued]>
[2025-05-28T08:53:58.856+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_etl_pipeline.analyze_data scheduled__2025-05-27T06:00:00+00:00 [queued]>
[2025-05-28T08:53:58.857+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2025-05-28T08:53:58.870+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): analyze_data> on 2025-05-27 06:00:00+00:00
[2025-05-28T08:53:58.881+0000] {standard_task_runner.py:57} INFO - Started process 14458 to run task
[2025-05-28T08:53:58.886+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'csv_etl_pipeline', 'analyze_data', 'scheduled__2025-05-27T06:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/csv_etl_pipeline.py', '--cfg-path', '/tmp/tmptxeiuqn1']
[2025-05-28T08:53:58.887+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask analyze_data
[2025-05-28T08:53:58.942+0000] {task_command.py:416} INFO - Running <TaskInstance: csv_etl_pipeline.analyze_data scheduled__2025-05-27T06:00:00+00:00 [running]> on host fe2c11ded3dc
[2025-05-28T08:53:59.086+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Sefanosok' AIRFLOW_CTX_DAG_ID='csv_etl_pipeline' AIRFLOW_CTX_TASK_ID='analyze_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-27T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-27T06:00:00+00:00'
[2025-05-28T08:53:59.429+0000] {logging_mixin.py:154} INFO - Analysis report saved to /opt/***/data/processed/analysis_report_20250528_085359.txt
[2025-05-28T08:53:59.438+0000] {python.py:194} INFO - Done. Returned value was: /opt/***/data/processed/analysis_report_20250528_085359.txt
[2025-05-28T08:53:59.462+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=csv_etl_pipeline, task_id=analyze_data, execution_date=20250527T060000, start_date=20250528T085358, end_date=20250528T085359
[2025-05-28T08:53:59.507+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-28T08:53:59.546+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
